Test

diff --git a/.github/actions/artifacts_build/action.yml b/.github/actions/artifacts_build/action.yml
--- a/.github/actions/artifacts_build/action.yml
+++ b/.github/actions/artifacts_build/action.yml
@@ -37,26 +37,26 @@ runs:
   using: "composite"
   steps:
     - name: Action verification
-      if: ${{ (inputs.load_image == false || inputs.load_image == 'false') && (inputs.push_image == false || inputs.push_image == 'false') }}
-      shell: bash
-      run: |
-        echo "At least one of push_image or load_image must be true" 
-        exit 1
+    #   if: ${{ (inputs.load_image == false || inputs.load_image == 'false') && (inputs.push_image == false || inputs.push_image == 'false') }}
+    #   shell: bash
+    #   run: |
+    #     echo "At least one of push_image or load_image must be true" 
+    #     exit 1
 
-    - name: Set up
-      uses: ./.github/actions/set_up
-      with:
-        python_version: ${{ inputs.python_version }}
-        package_name: ${{ inputs.package_name }}
-        os: ${{ inputs.os }}
-        run_unit_tests: true
+    # - name: Set up
+    #   uses: ./.github/actions/set_up
+    #   with:
+    #     python_version: ${{ inputs.python_version }}
+    #     package_name: ${{ inputs.package_name }}
+    #     os: ${{ inputs.os }}
+    #     run_unit_tests: true
 
-    - name: Configure AWS Credentials
-      if: ${{ inputs.push_image == true || inputs.push_image == 'true' }}
-      uses: aws-actions/configure-aws-credentials@v4
-      with:
-        role-to-assume: ${{ inputs.snapshot-ecr-role }}
-        aws-region: ${{ inputs.aws-region }}
+    # - name: Configure AWS Credentials
+    #   if: ${{ inputs.push_image == true || inputs.push_image == 'true' }}
+    #   uses: aws-actions/configure-aws-credentials@v4
+    #   with:
+    #     role-to-assume: ${{ inputs.snapshot-ecr-role }}
+    #     aws-region: ${{ inputs.aws-region }}
 
     - name: Install Dependencies and Build Wheel
       id: staging_wheel_build
@@ -67,41 +67,41 @@ runs:
         cd ./aws-opentelemetry-distro
         python -m build --outdir ../dist
 
-    - name: Set up QEMU
-      uses: docker/setup-qemu-action@v3
+    # - name: Set up QEMU
+    #   uses: docker/setup-qemu-action@v3
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
+    # - name: Set up Docker Buildx
+    #   uses: docker/setup-buildx-action@v3
 
-    - name: Login to private AWS ECR
-      if: ${{ inputs.push_image == true || inputs.push_image == 'true' }}
-      uses: docker/login-action@v3
-      with:
-        registry: ${{ inputs.image_registry }}
-      env:
-        AWS_REGION: ${{ inputs.aws-region }}
+    # - name: Login to private AWS ECR
+    #   if: ${{ inputs.push_image == true || inputs.push_image == 'true' }}
+    #   uses: docker/login-action@v3
+    #   with:
+    #     registry: ${{ inputs.image_registry }}
+    #   env:
+    #     AWS_REGION: ${{ inputs.aws-region }}
 
-    # Per https://docs.aws.amazon.com/AmazonECR/latest/public/docker-pull-ecr-image.html, it is possible to
-    # make unauthorized calls to get public ECR images (needed to build the ADOT Python docker image), but
-    # it can fail if you previously authenticated to a public repo. Adding this step to log out, so we
-    # ensure we can make unauthenticated call. This is important for making the pr_build workflow run on
-    # PRs created from forked repos.
-    - name: Logout of public AWS ECR
-      shell: bash
-      run: docker logout public.ecr.aws
+    # # Per https://docs.aws.amazon.com/AmazonECR/latest/public/docker-pull-ecr-image.html, it is possible to
+    # # make unauthorized calls to get public ECR images (needed to build the ADOT Python docker image), but
+    # # it can fail if you previously authenticated to a public repo. Adding this step to log out, so we
+    # # ensure we can make unauthenticated call. This is important for making the pr_build workflow run on
+    # # PRs created from forked repos.
+    # - name: Logout of public AWS ECR
+    #   shell: bash
+    #   run: docker logout public.ecr.aws
 
-    - name: Build and push image according to input
-      uses: docker/build-push-action@v5
-      with:
-        push: ${{ inputs.push_image }}
-        context: .
-        file: ./Dockerfile
-        platforms: linux/amd64
-        tags: ${{ inputs.image_uri_with_tag }}
-        load: ${{ inputs.load_image }}
+    # - name: Build and push image according to input
+    #   uses: docker/build-push-action@v5
+    #   with:
+    #     push: ${{ inputs.push_image }}
+    #     context: .
+    #     file: ./Dockerfile
+    #     platforms: linux/amd64
+    #     tags: ${{ inputs.image_uri_with_tag }}
+    #     load: ${{ inputs.load_image }}
 
-    - name: Perform image scan
-      uses: ./.github/actions/image_scan
-      with:
-        image-ref: ${{ inputs.image_uri_with_tag }}
-        severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
+    # - name: Perform image scan
+    #   uses: ./.github/actions/image_scan
+    #   with:
+    #     image-ref: ${{ inputs.image_uri_with_tag }}
+    #     severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
